

#!/bin/python

# ======== Imports.
from plover.system import english_stenotype as e  # type: ignore
# Alternatively
#    from plover import system as e
# can be used too, but then it will only work in Plover and only if the correct system is set.

from plover_python_dictionary_lib import get_context_from_system

# ======== Boilerplate to set up objects.
context=get_context_from_system(e)
s=context.SingleDictionary
stroke=context.stroke
translation=context.translation

# ======== Define constants.
#leader_stroke="TP*EURPBG" # finger*
#leader_stroke_2="TP*EURPBGS" # fingers*

# s(...): Creates a Dictionary object from a dict (or a list, for example, ["S"] is equivalent to {"S": "S"})

FSConsonantsAndMitras=s({
"KWFPLT": "{^क़}",
"KWAUFPLT": "{^क़ा}",
"KWEUFPLT": "{^क़ि}",
"KWAOEFPLT": "{^क़ी}",
"KWAOFPLT": "{^क़ु}",
"KWUFPLT": "{^क़ू}",
"KWEFPLT": "{^क़ृ}",
"KWAEUFPLT": "{^क़े}",
"KWAOEUFPLT": "{^क़ै}",
"KWOFPLT": "{^क़ो}",
"KWAOUFPLT": "{^क़ौ}",
"WHFPLT": "{^ख़}",
"WHAUFPLT": "{^ख़ा}",
"WHEUFPLT": "{^ख़ि}",
"WHAOEFPLT": "{^ख़ी}",
"WHAOFPLT": "{^ख़ु}",
"WHUFPLT": "{^ख़ू}",
"WHEFPLT": "{^ख़ृ}",
"WHAEUFPLT": "{^ख़े}",
"WHAOEUFPLT": "{^ख़ै}",
"WHOFPLT": "{^ख़ो}",
"WHAOUFPLT": "{^ख़ौ}",
"KPHRFPLT": "{^ग़}",
"KPHRAUFPLT": "{^ग़ा}",
"KPHREUFPLT": "{^ग़ि}",
"KPHRAOEFPLT": "{^ग़ी}",
"KPHRAOFPLT": "{^ग़ु}",
"KPHRUFPLT": "{^ग़ू}",
"KPHREFPLT": "{^ग़ृ}",
"KPHRAEUFPLT": "{^ग़े}",
"KPHRAOEUFPLT": "{^ग़ै}",
"KPHROFPLT": "{^ग़ो}",
"KPHRAOUFPLT": "{^ग़ौ}",
"KPWFPLT": "{^ङ}",
"KPWAUFPLT": "{^ङा}",
"KPWEUFPLT": "{^ङि}",
"KPWAOEFPLT": "{^ङी}",
"KPWAOFPLT": "{^ङु}",
"KPWUFPLT": "{^ङू}",
"KPWEFPLT": "{^ङृ}",
"KPWAEUFPLT": "{^ङे}",
"KPWAOEUFPLT": "{^ङै}",
"KPWOFPLT": "{^ङो}",
"KPWAOUFPLT": "{^ङौ}",
"STPHAUFPLT": "{^ञा}",
"STPHFPLT": "{^ञ}",
"STPHEUFPLT": "{^ञि}",
"STPHAOEFPLT": "{^ञी}",
"STPHAOFPLT": "{^ञु}",
"STPHUFPLT": "{^ञू}",
"STPHEFPLT": "{^ञृ}",
"STPHAEUFPLT": "{^ञे}",
"STPHAOEUFPLT": "{^ञै}",
"STPHOFPLT": "{^ञो}",
"STPHAOUFPLT": "{^ञौ}",
"TPHRFPLT": "{^ण}",
"TPHRAUFPLT": "{^णा}",
"TPHREUFPLT": "{^णि}",
"TPHRAOEFPLT": "{^णी}",
"TPHRAOFPLT": "{^णु}",
"TPHRUFPLT": "{^णू}",
"TPHREFPLT": "{^णृ}",
"TPHRAEUFPLT": "{^णे}",
"TPHRAOEUFPLT": "{^णै}",
"TPHROFPLT": "{^णो}",
"TPHRAOUFPLT": "{^णौ}",
"SKHRFPLT": "{^ष}",
"SKHRAUFPLT": "{^षा}",
"SKHREUFPLT": "{^षि}",
"SKHRAOEFPLT": "{^षी}",
"SKHRAOFPLT": "{^षु}",
"SKHRUFPLT": "{^षू}",
"SKHREFPLT": "{^षृ}",
"SKHRAEUFPLT": "{^षे}",
"SKHRAOEUFPLT": "{^षै}",
"SKHROFPLT": "{^षो}",
"SKHRAOUFPLT": "{^षौ}"
})

FSConsonantsWithChandrabindu=s({
"KWFPLT": "{^क़}",
"KWAUFPLT": "{^क़ा}",
"KWAOFPLT": "{^क़ु}",
"KWUFPLT": "{^क़ू}",
"KWEFPLT": "{^क़ृ}",
"WHFPLT": "{^ख़}",
"WHAUFPLT": "{^ख़ा}",
"WHAOFPLT": "{^ख़ु}",
"WHUFPLT": "{^ख़ू}",
"WHEFPLT": "{^ख़ृ}",
"KPHRFPLT": "{^ग़}",
"KPHRAUFPLT": "{^ग़ा}",
"KPHRAOFPLT": "{^ग़ु}",
"KPHRUFPLT": "{^ग़ू}",
"KPHREFPLT": "{^ग़ृ}",
"KPWFPLT": "{^ङ}",
"KPWAUFPLT": "{^ङा}",
"KPWAOFPLT": "{^ङु}",
"KPWUFPLT": "{^ङू}",
"KPWEFPLT": "{^ङृ}",
"STPHFPLT": "{^ञ}",
"STPHAUFPLT": "{^ञा}",
"STPHAOFPLT": "{^ञु}",
"STPHUFPLT": "{^ञू}",
"STPHEFPLT": "{^ञृ}",
"TPHRFPLT": "{^ण}",
"TPHRAUFPLT": "{^णा}",
"TPHRAOFPLT": "{^णु}",
"TPHRUFPLT": "{^णू}",
"TPHREFPLT": "{^णृ}",
"SKHRFPLT": "{^ष}",
"SKHRAUFPLT": "{^षा}",
"SKHRAOFPLT": "{^षु}",
"SKHRUFPLT": "{^षू}",
"SKHREFPLT": "{^षृ}"
})

FSConsonantsWithBindu=s({
"KWEUFPLT": "{^क़ि}",
"KWAOEFPLT": "{^क़ी}",
"KWAEUFPLT": "{^क़े}",
"KWAOEUFPLT": "{^क़ै}",
"KWOFPLT": "{^क़ो}",
"KWAOUFPLT": "{^क़ौ}",  
"WHEUFPLT": "{^ख़ि}",
"WHAOEFPLT": "{^ख़ी}",
"WHAEUFPLT": "{^ख़े}",
"WHAOEUFPLT": "{^ख़ै}",
"WHOFPLT": "{^ख़ो}",
"WHAOUFPLT": "{^ख़ौ}",
"KPHREUFPLT": "{^ग़ि}",
"KPHRAOEFPLT": "{^ग़ी}",
"KPHRAEUFPLT": "{^ग़े}",
"KPHRAOEUFPLT": "{^ग़ै}",
"KPHROFPLT": "{^ग़ो}",
"KPHRAOUFPLT": "{^ग़ौ}", 
"KPWEUFPLT": "{^ङि}",
"KPWAOEFPLT": "{^ङी}",
"KPWAEUFPLT": "{^ङे}",
"KPWAOEUFPLT": "{^ङै}",
"KPWOFPLT": "{^ङो}",
"KPWAOUFPLT": "{^ङौ}",
"STPHEUFPLT": "{^ञि}",
"STPHAOEFPLT": "{^ञी}",
"STPHAEUFPLT": "{^ञे}",
"STPHAOEUFPLT": "{^ञै}",
"STPHOFPLT": "{^ञो}",
"STPHAOUFPLT": "{^ञौ}",
"TPHREUFPLT": "{^णि}",
"TPHRAOEFPLT": "{^णी}",
"TPHRAEUFPLT": "{^णे}",
"TPHRAOEUFPLT": "{^णै}",
"TPHROFPLT": "{^णो}",
"TPHRAOUFPLT": "{^णौ}",
"SKHREUFPLT": "{^षि}",
"SKHRAOEFPLT": "{^षी}",
"SKHRAEUFPLT": "{^षे}",
"SKHRAOEUFPLT": "{^षै}",
"SKHROFPLT": "{^षो}",
"SKHRAOUFPLT": "{^षौ}"
})

FSBaseConsonants=s({
"KWFPLT": "{^क़}",
"WHFPLT": "{^ख़}",
"KPHRFPLT": "{^ग़}",
"KPWFPLT": "{^ङ}",
"STPHFPLT": "{^ञ}",
"TPHRFPLT": "{^ण}",
"SKHRFPLT": "{^ष}",
})


ConsonantsAndMitras=s({
"K": "{^क}",
"KAU": "{^का}",
"KEU": "{^कि}",
"KAOE": "{^की}",
"KAO": "{^कु}",
"KU": "{^कू}",
"KE": "{^कृ}",
"KAEU": "{^के}",
"KAOEU": "{^कै}",
"KO": "{^को}",
"KAOU": "{^कौ}",
"KWH": "{^ख}",
"KWHAU": "{^खा}",
"KWHEU": "{^खि}",
"KWHAOE": "{^खी}",
"KWHAO": "{^खु}",
"KWHU": "{^खू}",
"KWHE": "{^खृ}",
"KWHAEU": "{^खे}",
"KWHAOEU": "{^खै}",
"KWHO": "{^खो}",
"KWHAOU": "{^खौ}",
"KP": "{^ग}",
"KPAU": "{^गा}",
"KPEU": "{^गि}",
"KPAOE": "{^गी}",
"KPAO": "{^गु}",
"KPU": "{^गू}",
"KPE": "{^गृ}",
"KPAEU": "{^गे}",
"KPAOEU": "{^गै}",
"KPO": "{^गो}",
"KPAOU": "{^गौ}",
"KPH": "{^घ}",
"KPHAU": "{^घा}",
"KPHEU": "{^घि}",
"KPHAOE": "{^घी}",
"KPHAO": "{^घु}",
"KPHU": "{^घू}",
"KPHE": "{^घृ}",
"KPHAEU": "{^घे}",
"KPHAOEU": "{^घै}",
"KPHO": "{^घो}",
"KPHAOU": "{^घौ}",
"KH": "{^च}",
"KHAU": "{^चा}",
"KHEU": "{^चि}",
"KHAOE": "{^ची}",
"KHAO": "{^चु}",
"KHU": "{^चू}",
"KHE": "{^चृ}",
"KHAEU": "{^चे}",
"KHAOEU": "{^चै}",
"KHO": "{^चो}",
"KHAOU": "{^चौ}",
"KHR": "{^छ}",
"KHRAU": "{^छा}",
"KHREU": "{^छि}",
"KHRAOE": "{^छी}",
"KHRAO": "{^छु}",
"KHRU": "{^छू}",
"KHRE": "{^छृ}",
"KHRAEU": "{^छे}",
"KHRAOEU": "{^छै}",
"KHRO": "{^छो}",
"KHRAOU": "{^छौ}",
"SKWR": "{^ज}",
"SKWRAU": "{^जा}",
"SKWREU": "{^जि}",
"SKWRAOE": "{^जी}",
"SKWRAO": "{^जु}",
"SKWRU": "{^जू}",
"SKWRE": "{^जृ}",
"SKWRAEU": "{^जे}",
"SKWRAOEU": "{^जै}",
"SKWRO": "{^जो}",
"SKWRAOU": "{^जौ}",
"SWR": "{^ज़}",
"SWRAU": "{^ज़ा}",
"SWREU": "{^ज़ि}",
"SWRAOE": "{^ज़ी}",
"SWRAO": "{^ज़ु}",
"SWRU": "{^ज़ू}",
"SWRE": "{^ज़ृ}",
"SWRAEU": "{^ज़े}",
"SWRAOEU": "{^ज़ै}",
"SWRO": "{^ज़ो}",
"SWRAOU": "{^ज़ौ}",
"THR": "{^ठ}",
"THRAU": "{^ठा}",
"THREU": "{^ठि}",
"THRAOE": "{^ठी}",
"THRAO": "{^ठु}",
"THRU": "{^ठू}",
"THRE": "{^ठृ}",
"THRAEU": "{^ठे}",
"THRAOEU": "{^ठै}",
"THRO": "{^ठो}",
"THRAOU": "{^ठौ}",
"TH": "{^थ}",
"THAU": "{^था}",
"THEU": "{^थि}",
"THAOE": "{^थी}",
"THAO": "{^थु}",
"THU": "{^थू}",
"THE": "{^थृ}",
"THAEU": "{^थे}",
"THAOEU": "{^थै}",
"THO": "{^थो}",
"THAOU": "{^थौ}",
"PWH": "{^भ}",
"PWHAU": "{^भा}",
"PWHEU": "{^भि}",
"PWHAOE": "{^भी}",
"PWHAO": "{^भु}",
"PWHU": "{^भू}",
"PWHE": "{^भृ}",
"PWHAEU": "{^भे}",
"PWHAOEU": "{^भै}",
"PWHO": "{^भो}",
"PWHAOU": "{^भौ}",
"SH": "{^श}",
"SHAU": "{^शा}",
"SHEU": "{^शि}",
"SHAOE": "{^शी}",
"SHAO": "{^शु}",
"SHU": "{^शू}",
"SHE": "{^शृ}",
"SHAEU": "{^शे}",
"SHAOEU": "{^शै}",
"SHO": "{^शो}",
"SHAOU": "{^शौ}",
"SKWHR": "{^झ}",
"SKWHRAU": "{^झा}",
"SKWHREU": "{^झि}",
"SKWHRAOE": "{^झी}",
"SKWHRAO": "{^झु}",
"SKWHRU": "{^झू}",
"SKWHRE": "{^झृ}",
"SKWHRAEU": "{^झे}",
"SKWHRAOEU": "{^झै}",
"SKWHRO": "{^झो}",
"SKWHRAOU": "{^झौ}",
"TR": "{^ट}",
"TRAU": "{^टा}",
"TREU": "{^टि}",
"TRAOE": "{^टी}",
"TRAO": "{^टु}",
"TRU": "{^टू}",
"TRE": "{^टृ}",
"TRAEU": "{^टे}",
"TRAOEU": "{^टै}",
"TRO": "{^टो}",
"TRAOU": "{^टौ}",
"TKHR": "{^ढ}",
"TKHRAU": "{^ढा}",
"TKHREU": "{^ढि}",
"TKHRAOE": "{^ढी}",
"TKHRAO": "{^ढु}",
"TKHRU": "{^ढू}",
"TKHRE": "{^ढृ}",
"TKHRAEU": "{^ढे}",
"TKHRAOEU": "{^ढै}",
"TKHRO": "{^ढो}",
"TKHRAOU": "{^ढौ}",
"TKR": "{^ड}",
"TKRAU": "{^डा}",
"TKREU": "{^डि}",
"TKRAOE": "{^डी}",
"TKRAO": "{^डु}",
"TKRU": "{^डू}",
"TKRE": "{^डृ}",
"TKRAEU": "{^डे}",
"TKRAOEU": "{^डै}",
"TKRO": "{^डो}",
"TKRAOU": "{^डौ}",
"WR": "{^ड़}",
"WRAU": "{^ड़ा}",
"WREU": "{^ड़ि}",
"WRAOE": "{^ड़ी}",
"WRAO": "{^ड़ु}",
"WRU": "{^ड़ू}",
"WRE": "{^ड़ृ}",
"WRAEU": "{^ड़े}",
"WRAOEU": "{^ड़ै}",
"WRO": "{^ड़ो}",
"WRAOU": "{^ड़ौ}",
"WHR": "{^ढ़}",
"WHRAU": "{^ढ़ा}",
"WHREU": "{^ढ़ि}",
"WHRAOE": "{^ढ़ी}",
"WHRAO": "{^ढ़ु}",
"WHRU": "{^ढ़ू}",
"WHRE": "{^ढ़ृ}",
"WHRAEU": "{^ढ़े}",
"WHRAOEU": "{^ढ़ै}",
"WHRO": "{^ढ़ो}",
"WHRAOU": "{^ढ़ौ}",
"T": "{^त}",
"TAU": "{^ता}",
"TEU": "{^ति}",
"TAOE": "{^ती}",
"TAO": "{^तु}",
"TU": "{^तू}",
"TE": "{^तृ}",
"TAEU": "{^ते}",
"TAOEU": "{^तै}",
"TO": "{^तो}",
"TAOU": "{^तौ}",
"TK": "{^द}",
"TKAU": "{^दा}",
"TKEU": "{^दि}",
"TKAOE": "{^दी}",
"TKAO": "{^दु}",
"TKU": "{^दू}",
"TKE": "{^दृ}",
"TKAEU": "{^दे}",
"TKAOEU": "{^दै}",
"TKO": "{^दो}",
"TKAOU": "{^दौ}",
"TKH": "{^ध}",
"TKHAU": "{^धा}",
"TKHEU": "{^धि}",
"TKHAOE": "{^धी}",
"TKHAO": "{^धु}",
"TKHU": "{^धू}",
"TKHE": "{^धृ}",
"TKHAEU": "{^धे}",
"TKHAOEU": "{^धै}",
"TKHO": "{^धो}",
"TKHAOU": "{^धौ}",
"TPH": "{^न}",
"TPHAU": "{^ना}",
"TPHEU": "{^नि}",
"TPHAOE": "{^नी}",
"TPHAO": "{^नु}",
"TPHU": "{^नू}",
"TPHE": "{^नृ}",
"TPHAEU": "{^ने}",
"TPHAOEU": "{^नै}",
"TPHO": "{^नो}",
"TPHAOU": "{^नौ}",
"P": "{^प}",
"PAU": "{^पा}",
"PEU": "{^पि}",
"PAOE": "{^पी}",
"PAO": "{^पु}",
"PU": "{^पू}",
"PE": "{^पृ}",
"PAEU": "{^पे}",
"PAOEU": "{^पै}",
"PO": "{^पो}",
"PAOU": "{^पौ}",
"TP": "{^फ़}",
"TPAU": "{^फ़ा}",
"TPEU": "{^फ़ि}",
"TPAOE": "{^फ़ी}",
"TPAO": "{^फ़ु}",
"TPU": "{^फ़ू}",
"TPE": "{^फ़ृ}",
"TPAEU": "{^फ़े}",
"TPAOEU": "{^फ़ै}",
"TPO": "{^फ़ो}",
"TPAOU": "{^फ़ौ}",
"PHR": "{^फ}",
"PHRAU": "{^फा}",
"PHREU": "{^फि}",
"PHRAOE": "{^फी}",
"PHRAO": "{^फु}",
"PHRU": "{^फू}",
"PHRE": "{^फृ}",
"PHRAEU": "{^फे}",
"PHRAOEU": "{^फै}",
"PHRO": "{^फो}",
"PHRAOU": "{^फौ}",
"PW": "{^ब}",
"PWAU": "{^बा}",
"PWEU": "{^बि}",
"PWAOE": "{^बी}",
"PWAO": "{^बु}",
"PWU": "{^बू}",
"PWE": "{^बृ}",
"PWAEU": "{^बे}",
"PWAOEU": "{^बै}",
"PWO": "{^बो}",
"PWAOU": "{^बौ}",
"PH": "{^म}",
"PHAU": "{^मा}",
"PHEU": "{^मि}",
"PHAOE": "{^मी}",
"PHAO": "{^मु}",
"PHU": "{^मू}",
"PHE": "{^मृ}",
"PHAEU": "{^मे}",
"PHAOEU": "{^मै}",
"PHO": "{^मो}",
"PHAOU": "{^मौ}",
"KWR": "{^य}",
"KWRAU": "{^या}",
"KWREU": "{^यि}",
"KWRAOE": "{^यी}",
"KWRAO": "{^यु}",
"KWRU": "{^यू}",
"KWRE": "{^यृ}",
"KWRAEU": "{^ये}",
"KWRAOEU": "{^यै}",
"KWRO": "{^यो}",
"KWRAOU": "{^यौ}",
"R": "{^र}",
"RAU": "{^रा}",
"REU": "{^रि}",
"RAOE": "{^री}",
"RAO": "{^रु}",
"RU": "{^रू}",
"RE": "{^रृ}",
"RAEU": "{^रे}",
"RAOEU": "{^रै}",
"RO": "{^रो}",
"RAOU": "{^रौ}",
"HR": "{^ल}",
"HRAU": "{^ला}",
"HREU": "{^लि}",
"HRAOE": "{^ली}",
"HRAO": "{^लु}",
"HRU": "{^लू}",
"HRE": "{^लृ}",
"HRAEU": "{^ले}",
"HRAOEU": "{^लै}",
"HRO": "{^लो}",
"HRAOU": "{^लौ}",
"W": "{^व}",
"WAU": "{^वा}",
"WEU": "{^वि}",
"WAOE": "{^वी}",
"WAO": "{^वु}",
"WU": "{^वू}",
"WE": "{^वृ}",
"WAEU": "{^वे}",
"WAOEU": "{^वै}",
"WO": "{^वो}",
"WAOU": "{^वौ}",
"S": "{^स}",
"SAU": "{^सा}",
"SEU": "{^सि}",
"SAOE": "{^सी}",
"SAO": "{^सु}",
"SU": "{^सू}",
"SE": "{^सृ}",
"SAEU": "{^से}",
"SAOEU": "{^सै}",
"SO": "{^सो}",
"SAOU": "{^सौ}",
"H": "{^ह}",
"HAU": "{^हा}",
"HEU": "{^हि}",
"HAOE": "{^ही}",
"HAO": "{^हु}",
"HU": "{^हू}",
"HE": "{^हृ}",
"HAEU": "{^हे}",
"HAOEU": "{^है}",
"HO": "{^हो}",
"HAOU": "{^हौ}"
        })

VowelsStandalone=s({
"A*": "अ",
"A*EU": "ए",
"AO*": "उ",
"AO*E": "ई",
"AO*EU": "ऐ",
"AO*U": "औ",
"A*U": "आ",
"*E": "ऋ",
"*EU": "इ",
"O*": "ओ",
"*U": "ऊ"
        })

Vowels=s({
"A": "{^अ}",
"AEU": "{^ए}",
"AO": "{^उ}",
"AOE": "{^ई}",
"AOEU": "{^ऐ}",
"AOU": "{^औ}",
"AU": "{^आ}",
"E": "{^ऋ}",
"EU": "{^इ}",
"O": "{^ओ}",
"U": "{^ऊ}"
        })

BaseConsonants=s({
"K": "{^क}",
"KWH": "{^ख}",
"KP": "{^ग}",
"KPH": "{^घ}",
"KH": "{^च}",
"KHR": "{^छ}",
"SKWR": "{^ज}",
"SWR": "{^ज़}",
"THR": "{^ठ}",
"TH": "{^थ}",
"PWH": "{^भ}",
"SH": "{^श}",
"SKWHR": "{^झ}",
"TR": "{^ट}",
"TKHR": "{^ढ}",
"TKR": "{^ड}",
"WR": "{^ड़}",
"WHR": "{^ढ़}",
"T": "{^त}",
"TK": "{^द}",
"TKH": "{^ध}",
"TPH": "{^न}",
"P": "{^प}",
"TP": "{^फ़}",
"PHR": "{^फ}",
"PW": "{^ब}",
"PH": "{^म}",
"KWR": "{^य}",
"R": "{^र}",
"HR": "{^ल}",
"W": "{^व}",
"S": "{^स}",
"H": "{^ह}"
	})

ConsonantsWithChandraBindu=s({
"K": "{^क}",
"KAU": "{^का}",
"KAO": "{^कु}",
"KU": "{^कू}",
"KE": "{^कृ}",
"KWH": "{^ख}",
"KWHAU": "{^खा}",
"KWHAO": "{^खु}",
"KWHU": "{^खू}",
"KWHE": "{^खृ}",
"KP": "{^ग}",
"KPAU": "{^गा}",
"KPAO": "{^गु}",
"KPU": "{^गू}",
"KPE": "{^गृ}",
"KPH": "{^घ}",
"KPHAU": "{^घा}",
"KPHAO": "{^घु}",
"KPHU": "{^घू}",
"KPHE": "{^घृ}",
"KH": "{^च}",
"KHAU": "{^चा}",
"KHAO": "{^चु}",
"KHU": "{^चू}",
"KHE": "{^चृ}",
"KHR": "{^छ}",
"KHRAU": "{^छा}",
"KHRAO": "{^छु}",
"KHRU": "{^छू}",
"KHRE": "{^छृ}",
"SKWR": "{^ज}",
"SKWRAU": "{^जा}",
"SKWRAO": "{^जु}",
"SKWRU": "{^जू}",
"SKWRE": "{^जृ}",
"SWR": "{^ज़}",
"SWRAU": "{^ज़ा}",
"SWRAO": "{^ज़ु}",
"SWRU": "{^ज़ू}",
"SWRE": "{^ज़ृ}",
"THR": "{^ठ}",
"THRAU": "{^ठा}",
"THRAO": "{^ठु}",
"THRU": "{^ठू}",
"THRE": "{^ठृ}",
"TH": "{^थ}",
"THAU": "{^था}",
"THAO": "{^थु}",
"THU": "{^थू}",
"THE": "{^थृ}",
"PWH": "{^भ}",
"PWHAU": "{^भा}",
"PWHAO": "{^भु}",
"PWHU": "{^भू}",
"PWHE": "{^भृ}",
"SH": "{^श}",
"SHAU": "{^शा}",
"SHAO": "{^शु}",
"SHU": "{^शू}",
"SHE": "{^शृ}",
"SKWHR": "{^झ}",
"SKWHRAU": "{^झा}",
"SKWHRAO": "{^झु}",
"SKWHRU": "{^झू}",
"SKWHRE": "{^झृ}",
"TR": "{^ट}",
"TRAU": "{^टा}",
"TRAO": "{^टु}",
"TRU": "{^टू}",
"TRE": "{^टृ}",
"TKHR": "{^ढ}",
"TKHRAU": "{^ढा}",
"TKHRAO": "{^ढु}",
"TKHRU": "{^ढू}",
"TKHRE": "{^ढृ}",
"TKR": "{^ड}",
"TKRAU": "{^डा}",
"TKRAO": "{^डु}",
"TKRU": "{^डू}",
"TKRE": "{^डृ}",
"WR": "{^ड़}",
"WRAU": "{^ड़ा}",
"WRAO": "{^ड़ु}",
"WRU": "{^ड़ू}",
"WRE": "{^ड़ृ}",
"WHR": "{^ढ़}",
"WHRAU": "{^ढ़ा}",
"WHRAO": "{^ढ़ु}",
"WHRU": "{^ढ़ू}",
"WHRE": "{^ढ़ृ}",
"T": "{^त}",
"TAU": "{^ता}",
"TAO": "{^तु}",
"TU": "{^तू}",
"TE": "{^तृ}",
"TK": "{^द}",
"TKAU": "{^दा}",
"TKAO": "{^दु}",
"TKU": "{^दू}",
"TKE": "{^दृ}",
"TKH": "{^ध}",
"TKHAU": "{^धा}",
"TKHAO": "{^धु}",
"TKHU": "{^धू}",
"TKHE": "{^धृ}",
"TPH": "{^न}",
"TPHAU": "{^ना}",
"TPHAO": "{^नु}",
"TPHU": "{^नू}",
"TPHE": "{^नृ}",
"P": "{^प}",
"PAU": "{^पा}",
"PAO": "{^पु}",
"PU": "{^पू}",
"PE": "{^पृ}",
"TP": "{^फ़}",
"TPAU": "{^फ़ा}",
"TPAO": "{^फ़ु}",
"TPU": "{^फ़ू}",
"TPE": "{^फ़ृ}",
"PHR": "{^फ}",
"PHRAU": "{^फा}",
"PHRAO": "{^फु}",
"PHRU": "{^फू}",
"PHRE": "{^फृ}",
"PW": "{^ब}",
"PWAU": "{^बा}",
"PWAO": "{^बु}",
"PWU": "{^बू}",
"PWE": "{^बृ}",
"PH": "{^म}",
"PHAU": "{^मा}",
"PHAO": "{^मु}",
"PHU": "{^मू}",
"PHE": "{^मृ}",
"KWR": "{^य}",
"KWRAU": "{^या}",
"KWRAO": "{^यु}",
"KWRU": "{^यू}",
"KWRE": "{^यृ}",
"R": "{^र}",
"RAU": "{^रा}",
"RAO": "{^रु}",
"RU": "{^रू}",
"RE": "{^रृ}",
"HR": "{^ल}",
"HRAU": "{^ला}",
"HRAO": "{^लु}",
"HRU": "{^लू}",
"HRE": "{^लृ}",
"W": "{^व}",
"WAU": "{^वा}",
"WAO": "{^वु}",
"WU": "{^वू}",
"WE": "{^वृ}",
"S": "{^स}",
"SAU": "{^सा}",
"SAO": "{^सु}",
"SU": "{^सू}",
"SE": "{^सृ}",
"H": "{^ह}",
"HAU": "{^हा}",
"HAO": "{^हु}",
"HU": "{^हू}",
"HE": "{^हृ}",
"A": "{^अ}",
"AEU": "{^ए}",
"AO": "{^उ}",
"AU": "{^आ}",
"E": "{^ऋ}",
"EU": "{^इ}",
"U": "{^ऊ}"
        })

ConsonantsWithBindu=s({
"KEU": "{^कि}",
"KAOE": "{^की}",
"KAEU": "{^के}",
"KAOEU": "{^कै}",
"KO": "{^को}",
"KAOU": "{^कौ}",
"KWHEU": "{^खि}",
"KWHAOE": "{^खी}",
"KWHAEU": "{^खे}",
"KWHAOEU": "{^खै}",
"KWHO": "{^खो}",
"KWHAOU": "{^खौ}",
"KPEU": "{^गि}",
"KPAOE": "{^गी}",
"KPAEU": "{^गे}",
"KPAOEU": "{^गै}",
"KPO": "{^गो}",
"KPAOU": "{^गौ}",
"KPHEU": "{^घि}",
"KPHAOE": "{^घी}",
"KPHAEU": "{^घे}",
"KPHAOEU": "{^घै}",
"KPHO": "{^घो}",
"KPHAOU": "{^घौ}",
"KHEU": "{^चि}",
"KHAOE": "{^ची}",
"KHAEU": "{^चे}",
"KHAOEU": "{^चै}",
"KHO": "{^चो}",
"KHAOU": "{^चौ}",
"KHREU": "{^छि}",
"KHRAOE": "{^छी}",
"KHRAEU": "{^छे}",
"KHRAOEU": "{^छै}",
"KHRO": "{^छो}",
"KHRAOU": "{^छौ}",
"SKWREU": "{^जि}",
"SKWRAOE": "{^जी}",
"SKWRAEU": "{^जे}",
"SKWRAOEU": "{^जै}",
"SKWRO": "{^जो}",
"SKWRAOU": "{^जौ}",
"SWREU": "{^ज़ि}",
"SWRAOE": "{^ज़ी}",
"SWRAEU": "{^ज़े}",
"SWRAOEU": "{^ज़ै}",
"SWRO": "{^ज़ो}",
"SWRAOU": "{^ज़ौ}",
"THREU": "{^ठि}",
"THRAOE": "{^ठी}",
"THRAEU": "{^ठे}",
"THRAOEU": "{^ठै}",
"THRO": "{^ठो}",
"THRAOU": "{^ठौ}",
"THEU": "{^थि}",
"THAOE": "{^थी}",
"THAEU": "{^थे}",
"THAOEU": "{^थै}",
"THO": "{^थो}",
"THAOU": "{^थौ}",
"PWHEU": "{^भि}",
"PWHAOE": "{^भी}",
"PWHAEU": "{^भे}",
"PWHAOEU": "{^भै}",
"PWHO": "{^भो}",
"PWHAOU": "{^भौ}",
"SHEU": "{^शि}",
"SHAOE": "{^शी}",
"SHAEU": "{^शे}",
"SHAOEU": "{^शै}",
"SHO": "{^शो}",
"SHAOU": "{^शौ}",
"SKWHREU": "{^झि}",
"SKWHRAOE": "{^झी}",
"SKWHRAEU": "{^झे}",
"SKWHRAOEU": "{^झै}",
"SKWHRO": "{^झो}",
"SKWHRAOU": "{^झौ}",
"TREU": "{^टि}",
"TRAOE": "{^टी}",
"TRAEU": "{^टे}",
"TRAOEU": "{^टै}",
"TRO": "{^टो}",
"TRAOU": "{^टौ}",
"TKHREU": "{^ढि}",
"TKHRAOE": "{^ढी}",
"TKHRAEU": "{^ढे}",
"TKHRAOEU": "{^ढै}",
"TKHRO": "{^ढो}",
"TKHRAOU": "{^ढौ}",
"TKREU": "{^डि}",
"TKRAOE": "{^डी}",
"TKRAEU": "{^डे}",
"TKRAOEU": "{^डै}",
"TKRO": "{^डो}",
"TKRAOU": "{^डौ}",
"WREU": "{^ड़ि}",
"WRAOE": "{^ड़ी}",
"WRAEU": "{^ड़े}",
"WRAOEU": "{^ड़ै}",
"WRO": "{^ड़ो}",
"WRAOU": "{^ड़ौ}",
"WHREU": "{^ढ़ि}",
"WHRAOE": "{^ढ़ी}",
"WHRAEU": "{^ढ़े}",
"WHRAOEU": "{^ढ़ै}",
"WHRO": "{^ढ़ो}",
"WHRAOU": "{^ढ़ौ}",
"TEU": "{^ति}",
"TAOE": "{^ती}",
"TAEU": "{^ते}",
"TAOEU": "{^तै}",
"TO": "{^तो}",
"TAOU": "{^तौ}",
"TKEU": "{^दि}",
"TKAOE": "{^दी}",
"TKAEU": "{^दे}",
"TKAOEU": "{^दै}",
"TKO": "{^दो}",
"TKAOU": "{^दौ}",
"TKHEU": "{^धि}",
"TKHAOE": "{^धी}",
"TKHAEU": "{^धे}",
"TKHAOEU": "{^धै}",
"TKHO": "{^धो}",
"TKHAOU": "{^धौ}",
"TPHEU": "{^नि}",
"TPHAOE": "{^नी}",
"TPHAEU": "{^ने}",
"TPHAOEU": "{^नै}",
"TPHO": "{^नो}",
"TPHAOU": "{^नौ}",
"PEU": "{^पि}",
"PAOE": "{^पी}",
"PAEU": "{^पे}",
"PAOEU": "{^पै}",
"PO": "{^पो}",
"PAOU": "{^पौ}",
"TPEU": "{^फ़ि}",
"TPAOE": "{^फ़ी}",
"TPAEU": "{^फ़े}",
"TPAOEU": "{^फ़ै}",
"TPO": "{^फ़ो}",
"TPAOU": "{^फ़ौ}",
"PHREU": "{^फि}",
"PHRAOE": "{^फी}",
"PHRAEU": "{^फे}",
"PHRAOEU": "{^फै}",
"PHRO": "{^फो}",
"PHRAOU": "{^फौ}",
"PWEU": "{^बि}",
"PWAOE": "{^बी}",
"PWAEU": "{^बे}",
"PWAOEU": "{^बै}",
"PWO": "{^बो}",
"PWAOU": "{^बौ}",
"PHEU": "{^मि}",
"PHAOE": "{^मी}",
"PHAEU": "{^मे}",
"PHAOEU": "{^मै}",
"PHO": "{^मो}",
"PHAOU": "{^मौ}",
"KWREU": "{^यि}",
"KWRAOE": "{^यी}",
"KWRAEU": "{^ये}",
"KWRAOEU": "{^यै}",
"KWRO": "{^यो}",
"KWRAOU": "{^यौ}",
"REU": "{^रि}",
"RAOE": "{^री}",
"RAEU": "{^रे}",
"RAOEU": "{^रै}",
"RO": "{^रो}",
"RAOU": "{^रौ}",
"HREU": "{^लि}",
"HRAOE": "{^ली}",
"HRAEU": "{^ले}",
"HRAOEU": "{^लै}",
"HRO": "{^लो}",
"HRAOU": "{^लौ}",
"WEU": "{^वि}",
"WAOE": "{^वी}",
"WAEU": "{^वे}",
"WAOEU": "{^वै}",
"WO": "{^वो}",
"WAOU": "{^वौ}",
"SEU": "{^सि}",
"SAOE": "{^सी}",
"SAEU": "{^से}",
"SAOEU": "{^सै}",
"SO": "{^सो}",
"SAOU": "{^सौ}",
"HEU": "{^हि}",
"HAOE": "{^ही}",
"HAEU": "{^हे}",
"HAOEU": "{^है}",
"HO": "{^हो}",
"HAOU": "{^हौ}",
"AOE": "{^ई}",
"AOEU": "{^ऐ}",
"AOU": "{^औ}",
"O": "{^ओ}"
        })

#Added to base consonants to form conjuncts
Virama=s({
        '*': '{^्}'
	})

#Add to all consonants/consonants+mitra to ass visarg
Visarg=s({
    "-G": "{^ः}"
        })

#Add to all consonants/consonant+mitra where the default vowel nasalization would be a chandrabindu
Chandrabindu=s({
    "-B": "{^ँ}"
        })

#Add to all consonants/consonant+mitra where the default vowel nasalization would be a bindu
Bindu=s({
    "-B": "{^ं}"
        })

#Add to all consonants/consonant+mitra where other nasalization is required (conjunct, velar, palatal, etc. - see https://openbooks.lib.msu.edu/basichindi/chapter/nasal-sounds-in-hindi/).  Uses same character as "bindu".
Nasalization=s({
    "-PB": "{^ं}"
        })

#Add to all FS consonants/consonants+mitra to ass visarg
FSVisarg=s({
    "/-G": "{^ः}"
        })

#Add to all FS consonants/consonant+mitra where the default vowel nasalization would be a chandrabindu
FSChandrabindu=s({
    "/-B": "{^ँ}"
        })

#Add to all FS consonants/consonant+mitra where the default vowel nasalization would be a bindu
FSBindu=s({
    "/-B": "{^ं}"
        })

#Add to all FS consonants/consonant+mitra where other nasalization is required (conjunct, velar, palatal, etc. - see https://openbooks.lib.msu.edu/basichindi/chapter/nasal-sounds-in-hindi/).  Uses same character as "bindu".
FSNasalization=s({
    "/-PB": "{^ं}"
        })

#Separate stroke to add special characters (virama, visarg, chandrabindu,bindu, Nasalisation
SpecialCharacters=s({
        "SR*RBGS":"{^्}",
        "S*RBGS": "{^ः}",
        "KH*RBGS": "{^ँ}",
        "PW*RBGS": "{^ं}",
        "TPH*RBGS": "{^ं}"
        })

# ======== Main definitions.

# |: Compute the union of two dictionaries.
# *: Compute the (Cartesian) product of two dictionaries. The 2 adjacent strokes are merged.

#Define Base Strokes
dictionary =    ConsonantsAndMitras | \
                Vowels | \
                VowelsStandalone | \
                SpecialCharacters
#Define FingerSpelling FS Base Strokes
dictionary =    dictionary | \
                FSBaseConsonants |\
                FSConsonantsAndMitras |\
                FSConsonantsWithBindu |\
                FSConsonantsWithChandrabindu

#Add Virama option to all strokes
dictionary =    dictionary | \
                BaseConsonants*Virama | \
                FSBaseConsonants*Virama
                
#Add Visarg option to all strokes
dictionary =    dictionary | \
                ConsonantsAndMitras*Visarg | \
                FSConsonantsAndMitras*FSVisarg |\
                Vowels*Visarg

#Add Bindu/Chandrabindu to all strokes as appropriate
dictionary =    dictionary | \
                ConsonantsWithBindu*Bindu | \
                ConsonantsWithChandraBindu*Chandrabindu | \
                FSConsonantsWithBindu*FSBindu | \
                FSConsonantsWithChandrabindu*FSChandrabindu

#Add Consonant nasalisation to all strokes as appropriate
dictionary =    dictionary | \
                Vowels*Nasalization | \
                ConsonantsAndMitras*Nasalization | \
                FSConsonantsAndMitras*FSNasalization
                

# ======== More boilerplate (the lambda is required because plover-python-dictionary only accept objects with function type as the lookup function

lookup=lambda strokes: dictionary.lookup_tuple(strokes)
LONGEST_KEY=dictionary.longest_key

if __name__=="__main__":
    dictionary.print_items()
